sudo: required

language: go

services:
  - docker

before_install:
  - make build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push patricksanders/go-docker-hello;
    fi
