sudo: required

language: go

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

env:
  - GOLANG_VERSION=1.7
  - GOLANG_VERSION=1.8
  - GOLANG_VERSION=1.9
  - GOLANG_VERSION=1.10
  - GOLANG_VERSION=latest

script: make build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $TRAVIS_REPO_SLUG;
    fi
